//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vamp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vamp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp# remote connection error: {0}{1}|Something wrong with the amp# remote connection API with an error message.
        /// </summary>
        internal static string msgAmpRemoteError {
            get {
                return ResourceManager.GetString("msgAmpRemoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding exception logger|As in bind the application global exception logger.
        /// </summary>
        internal static string msgBindExceptionLogger {
            get {
                return ResourceManager.GetString("msgBindExceptionLogger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back|A tool-tip for a browser back button.
        /// </summary>
        internal static string msgBrowserBack {
            get {
                return ResourceManager.GetString("msgBrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit|A tool-tip for a browser exit button.
        /// </summary>
        internal static string msgBrowserExit {
            get {
                return ResourceManager.GetString("msgBrowserExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward|A tool-tip for a browser forward button.
        /// </summary>
        internal static string msgBrowserForward {
            get {
                return ResourceManager.GetString("msgBrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh|A tool-tip for a browser refresh button.
        /// </summary>
        internal static string msgBrowserRefresh {
            get {
                return ResourceManager.GetString("msgBrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel|As in a Cancel button.
        /// </summary>
        internal static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the TMDb client|As in configure the TMdbEasy client and get its configuration.
        /// </summary>
        internal static string msgConfigureTMDbClient {
            get {
                return ResourceManager.GetString("msgConfigureTMDbClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm|A short message indicating that a some action should be confirmed by the user.
        /// </summary>
        internal static string msgConfirm {
            get {
                return ResourceManager.GetString("msgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the photo album named: &apos;{0}&apos;?|A confirmation question for a photo album delete request.
        /// </summary>
        internal static string msgConfirmPhotoAlbumDelete {
            get {
                return ResourceManager.GetString("msgConfirmPhotoAlbumDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cache loading|As in data from the SQLite database is being cached in to the memory.
        /// </summary>
        internal static string msgDatabaseCacheLoading {
            get {
                return ResourceManager.GetString("msgDatabaseCacheLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database photo file information cache loading|As in data from the SQLite database from the V_PHOTOALBUM view is being cached in to the memory.
        /// </summary>
        internal static string msgDatabasePhotoCacheLoading {
            get {
                return ResourceManager.GetString("msgDatabasePhotoCacheLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..done.|As in some operation is done.
        /// </summary>
        internal static string msgDone {
            get {
                return ResourceManager.GetString("msgDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error|A message describing that some kind of error occurred..
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script error occurred on the database update|Something failed during running the database update script.
        /// </summary>
        internal static string msgErrorInScript {
            get {
                return ResourceManager.GetString("msgErrorInScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Chromium Embedded Framework settings.
        /// </summary>
        internal static string msgInitChromiumEmbeddedFrameworkSettings {
            get {
                return ResourceManager.GetString("msgInitChromiumEmbeddedFrameworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize database|As in initialize the SQLite database connection and do some caching.
        /// </summary>
        internal static string msgInitDatabase {
            get {
                return ResourceManager.GetString("msgInitDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize GeckoFx engine|As in initialize the GeckoFX web browser engine.
        /// </summary>
        internal static string msgInitGeckoFXEngine {
            get {
                return ResourceManager.GetString("msgInitGeckoFXEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize the VLC.DotNet|As in initialize the Vcl.DotNet library and underlying VLC native library.
        /// </summary>
        internal static string msgInitializeVLCDotNet {
            get {
                return ResourceManager.GetString("msgInitializeVLCDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given URL is invalid: &apos;{0}&apos;.|A navigation error occurred in a web browser form..
        /// </summary>
        internal static string msgInvalidURL {
            get {
                return ResourceManager.GetString("msgInvalidURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating|Rating for a item in a play list.
        /// </summary>
        internal static string msgItemRating {
            get {
                return ResourceManager.GetString("msgItemRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to start|A text describing a button tool-tip that jumps the playback to the start.
        /// </summary>
        internal static string msgJumToStart {
            get {
                return ResourceManager.GetString("msgJumToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Chromium Embedded Framework.
        /// </summary>
        internal static string msgLoadChromiumEmbeddedFramework {
            get {
                return ResourceManager.GetString("msgLoadChromiumEmbeddedFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization|As in localize the main form.
        /// </summary>
        internal static string msgLocalization {
            get {
                return ResourceManager.GetString("msgLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as watched?|A short (in text length) question whether or not to mark a file or a directory as watched.
        /// </summary>
        internal static string msgMarkItemAsWatched {
            get {
                return ResourceManager.GetString("msgMarkItemAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu|A tool-tip for a context menu button.
        /// </summary>
        internal static string msgMenu {
            get {
                return ResourceManager.GetString("msgMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database media location cache loading|As in data from the SQLite database from the MEDIALOCATION and from the PHOTOALBUM tables are being cached in to the memory.
        /// </summary>
        internal static string msgMsgDatabaseMediaLocationCacheLoading {
            get {
                return ResourceManager.GetString("msgMsgDatabaseMediaLocationCacheLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New photo album|A text describing a new photo album.
        /// </summary>
        internal static string msgNewPhotoAlbum {
            get {
                return ResourceManager.GetString("msgNewPhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next|A text describing a button tool-tip of a button to jump to a next item in the playback.
        /// </summary>
        internal static string msgNext {
            get {
                return ResourceManager.GetString("msgNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK|As in an OK button.
        /// </summary>
        internal static string msgOK {
            get {
                return ResourceManager.GetString("msgOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause|A text describing a button tool-tip that pauses the playback.
        /// </summary>
        internal static string msgPause {
            get {
                return ResourceManager.GetString("msgPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %|An indicator of percentage.
        /// </summary>
        internal static string msgPercentage {
            get {
                return ResourceManager.GetString("msgPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo album with the given name already exists|As in a photo album with the given name already exists.
        /// </summary>
        internal static string msgPhotoAlbumExists {
            get {
                return ResourceManager.GetString("msgPhotoAlbumExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit|A tool-tip for a photo album browser exit button.
        /// </summary>
        internal static string msgPhotoAlbumExit {
            get {
                return ResourceManager.GetString("msgPhotoAlbumExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next photo|A tool-tip to indicate that a button would select a next photo from a photo album.
        /// </summary>
        internal static string msgPhotoAlbumNext {
            get {
                return ResourceManager.GetString("msgPhotoAlbumNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous photo|A tool-tip to indicate that a button would select a previous photo from a photo album.
        /// </summary>
        internal static string msgPhotoAlbumPrevious {
            get {
                return ResourceManager.GetString("msgPhotoAlbumPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}: &apos;{2}&apos; [{3}]|A tool-tip for a position of a photo in a photo album, description for a photo and its take time.
        /// </summary>
        internal static string msgPhotoDescription {
            get {
                return ResourceManager.GetString("msgPhotoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate clockwise|A tool-tip to indicate that a button would rotate a photo clockwise.
        /// </summary>
        internal static string msgPhotoRotateClockwise {
            get {
                return ResourceManager.GetString("msgPhotoRotateClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate counterclockwise|A tool-tip to indicate that a button would rotate a photo counterclockwise.
        /// </summary>
        internal static string msgPhotoRotateCounterClockwise {
            get {
                return ResourceManager.GetString("msgPhotoRotateCounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play|As in a tool-tip to describe user clicking the play button.
        /// </summary>
        internal static string msgPlay {
            get {
                return ResourceManager.GetString("msgPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The beginning|A message describing that the playback should be started from the beginning.
        /// </summary>
        internal static string msgPlaybackFromThebeginng {
            get {
                return ResourceManager.GetString("msgPlaybackFromThebeginng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback position|A tool-tip for describing a text box with time.
        /// </summary>
        internal static string msgPlaybackPosition {
            get {
                return ResourceManager.GetString("msgPlaybackPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek|A slider with current playback position.
        /// </summary>
        internal static string msgPlaybackPositionSlider {
            get {
                return ResourceManager.GetString("msgPlaybackPositionSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback...|A message describing if something should be done for the playback.
        /// </summary>
        internal static string msgPlayBackThreeDots {
            get {
                return ResourceManager.GetString("msgPlayBackThreeDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous|A text describing a button tool-tip of a button to jump to a previous item in the playback.
        /// </summary>
        internal static string msgPrevious {
            get {
                return ResourceManager.GetString("msgPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue|A text describing a button tool-tip of a button to show only queued items in a play list.
        /// </summary>
        internal static string msgQueue {
            get {
                return ResourceManager.GetString("msgQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random|A text describing a button tool-tip of a button to toggle play list randomization.
        /// </summary>
        internal static string msgRandom {
            get {
                return ResourceManager.GetString("msgRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready|As in some operation is ready.
        /// </summary>
        internal static string msgReady {
            get {
                return ResourceManager.GetString("msgReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat|A text describing a button tool-tip of a button to toggle playback repeat mode.
        /// </summary>
        internal static string msgRepeat {
            get {
                return ResourceManager.GetString("msgRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind|A text describing a button tool-tip starts winding the playback backwards with a higher speed.
        /// </summary>
        internal static string msgRewind {
            get {
                return ResourceManager.GetString("msgRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue from {0}|A message describing a saved playback position to continue the playback from.
        /// </summary>
        internal static string msgSavedPlaybackPositionContinue {
            get {
                return ResourceManager.GetString("msgSavedPlaybackPositionContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to end|A text describing a button tool-tip that jumps the playback to the end. The playback window is closed..
        /// </summary>
        internal static string msgSeekEnd {
            get {
                return ResourceManager.GetString("msgSeekEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Album|A tool-tip message describing a button to select a music album.
        /// </summary>
        internal static string msgSelectAlbum {
            get {
                return ResourceManager.GetString("msgSelectAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder|A dialog requests a user to select a folder.
        /// </summary>
        internal static string msgSelectFolder {
            get {
                return ResourceManager.GetString("msgSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Script Files|*.sql|A filter for SQL script files.
        /// </summary>
        internal static string msgSQLFileFilter {
            get {
                return ResourceManager.GetString("msgSQLFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while running a SQL transaction to the database.|As in a some kind of error occurred while running an arbitrary SQL against the SQLite database.
        /// </summary>
        internal static string msgSQLSentenceError {
            get {
                return ResourceManager.GetString("msgSQLSentenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop|A text describing a button tool-tip that stops the playback and closes the playback window.
        /// </summary>
        internal static string msgStop {
            get {
                return ResourceManager.GetString("msgStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL|A tool-tip for a browser URL address.
        /// </summary>
        internal static string msgUrl {
            get {
                return ResourceManager.GetString("msgUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vamp# photo album editor|A title for the photo album editor.
        /// </summary>
        internal static string msgVampPhotoAlbumEditor {
            get {
                return ResourceManager.GetString("msgVampPhotoAlbumEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual styles|As in initializing the visual styles.
        /// </summary>
        internal static string msgVisualStyles {
            get {
                return ResourceManager.GetString("msgVisualStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VLC Library is missing. The playback will be aborted.|As in the VLC library (dll&apos;s and stuff) is missing, so no video playback will occur!.
        /// </summary>
        internal static string msgVLCLibMissing {
            get {
                return ResourceManager.GetString("msgVLCLibMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume: {0}%|As in a tool-tip to describe volume and its percentage value.
        /// </summary>
        internal static string msgVolumePercentage {
            get {
                return ResourceManager.GetString("msgVolumePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind|A text describing a button tool-tip starts winding the playback forward with a higher speed.
        /// </summary>
        internal static string msgWindForward {
            get {
                return ResourceManager.GetString("msgWindForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit|A tool-tip for a window close/exit button.
        /// </summary>
        internal static string msgWindowExit {
            get {
                return ResourceManager.GetString("msgWindowExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files|*.xml|A filter for XML (Extensible Markup Language) files.
        /// </summary>
        internal static string msgXMLFileFilter {
            get {
                return ResourceManager.GetString("msgXMLFileFilter", resourceCulture);
            }
        }
    }
}
